#!/usr/bin/env bash
#
# deploy-app.sh
#
# Deploys Istio, then Kong, then the hardened app onto the AKS cluster.
# It drives the cluster through "az aks command invoke", so no local kubectl or
# helm is required. The script is idempotent and safe to re-run.
#
# It reads the Auth0 domain and client id from Terraform outputs and injects
# them into the app config and the Content Security Policy, so the app is
# portable across tenants. After Kong gets its public IP, it syncs the Auth0
# callback URLs to that IP.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."
TF_DIR="$ROOT/terraform"
RG="${RESOURCE_GROUP:-rg-pam-governance}"
AKS="${AKS_NAME:-aks-pam-governance}"
ISTIO_REPO="https://istio-release.storage.googleapis.com/charts"
KONG_REPO="https://charts.konghq.com"

log()  { printf '%s\n' "$*"; }
invoke() { az aks command invoke -g "$RG" -n "$AKS" --query "logs" -o tsv "$@"; }

# --- Assemble the manifests and assets, templating tenant-specific values ---
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
cp "$ROOT/app/index.html" "$ROOT/app/style.css" "$ROOT/app/app.js" "$ROOT/app/config.js" "$ROOT/k8s/app.yaml" "$work/"

auth0_domain="$(terraform -chdir="$TF_DIR" output -raw auth0_domain 2>/dev/null || true)"
client_id="$(terraform -chdir="$TF_DIR" output -raw auth0_app_client_id 2>/dev/null || true)"
if [ -n "$auth0_domain" ] && [ -n "$client_id" ]; then
  log "Templating app config from Terraform outputs (domain=$auth0_domain)."
  cat > "$work/config.js" <<EOF
// Generated by scripts/deploy-app.sh from Terraform outputs.
window.APP_CONFIG = { auth0Domain: "$auth0_domain", auth0ClientId: "$client_id" };
EOF
  # Point the CSP connect-src/frame-src at this tenant's Auth0 domain.
  sed -i -E "s#https://[a-z0-9.-]+\.auth0\.com#https://$auth0_domain#g" "$work/app.yaml"
else
  log "Terraform outputs unavailable; using committed app/config.js."
fi

# --- 1. Istio (service mesh, mTLS) ---
log "Installing Istio (base and istiod)."
invoke --command "kubectl create namespace istio-system --dry-run=client -o yaml | kubectl apply -f - ; \
  helm status istio-base -n istio-system >/dev/null 2>&1 || helm install istio-base base --repo $ISTIO_REPO -n istio-system --set defaultRevision=default --wait --timeout 5m ; \
  helm status istiod -n istio-system >/dev/null 2>&1 || helm install istiod istiod --repo $ISTIO_REPO -n istio-system --wait --timeout 5m" >/dev/null
log "Istio ready."

# --- 2. Kong (edge API gateway, LoadBalancer) ---
log "Installing Kong as the edge load balancer."
invoke --command "kubectl create ns kong --dry-run=client -o yaml | kubectl apply -f - ; \
  kubectl label ns kong istio-injection=enabled --overwrite ; \
  helm status kong -n kong >/dev/null 2>&1 || helm install kong kong --repo $KONG_REPO -n kong --set ingressController.installCRDs=false --wait --timeout 6m" >/dev/null
log "Kong ready."

# --- 3. Hardened app ---
log "Deploying the app manifest and assets."
invoke \
  --file "$work/app.yaml" \
  --file "$work/index.html" \
  --file "$work/style.css" \
  --file "$work/app.js" \
  --file "$work/config.js" \
  --command "kubectl apply -f app.yaml ; \
    kubectl -n pam-governance create configmap app-files \
      --from-file=index.html --from-file=style.css --from-file=app.js --from-file=config.js \
      --dry-run=client -o yaml | kubectl apply -f - ; \
    kubectl -n pam-governance rollout restart deploy/app ; \
    kubectl -n pam-governance rollout status deploy/app --timeout=150s" >/dev/null
log "App deployed."

# --- 4. Wait for the Kong public IP (the LB is assigned after the pods are up) ---
log "Waiting for the Kong public IP."
ip=""
for _ in $(seq 1 30); do
  ip="$(invoke --command "kubectl -n kong get svc kong-kong-proxy -o jsonpath='{.status.loadBalancer.ingress[0].ip}'" | tr -d '[:space:]')"
  [ -n "$ip" ] && break
  sleep 10
done
[ -n "$ip" ] || { log "Kong load balancer IP not assigned yet. Re-run later."; exit 1; }
log "App online at http://${ip} (it redirects to https)."

# --- 5. Sync the Auth0 callback URLs to the Kong IP (needs the M2M env vars) ---
if [ -f "$TF_DIR/terraform.tfvars" ] && [ -n "${AUTH0_CLIENT_ID:-}" ] && [ -n "${AUTH0_CLIENT_SECRET:-}" ]; then
  log "Syncing Auth0 callbacks to http://${ip}."
  if grep -q '^app_url' "$TF_DIR/terraform.tfvars"; then
    sed -i -E "s#^app_url.*#app_url = \"http://${ip}\"#" "$TF_DIR/terraform.tfvars"
  else
    printf 'app_url = "http://%s"\n' "$ip" >> "$TF_DIR/terraform.tfvars"
  fi
  terraform -chdir="$TF_DIR" apply -target=auth0_client.app_spa -auto-approve \
    || log "Callback sync failed; run: terraform -chdir=terraform apply -target=auth0_client.app_spa"
else
  log "Skipping Auth0 callback sync (set AUTH0_* env vars and terraform.tfvars to enable)."
  log "Manual step: set app_url=\"http://${ip}\" and run terraform apply -target=auth0_client.app_spa."
fi
